sudo: required
dist: xenial
language: generic
install: git clone https://github.com/qubesos/qubes-builder ~/qubes-builder
script: ~/qubes-builder/scripts/travis-build
env:
 - DIST_DOM0=fc29 USE_QUBES_REPO_VERSION=4.1
